version: "3.9"
services:
  docs:
    image: python:3.10-slim
    volumes:
      - .:/docs
    working_dir: /docs
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install mkdocs-material mkdocs-mermaid2-plugin && 
             mkdocs serve --dev-addr=0.0.0.0:8000"

  game:
    depends_on: [network_lab]
    image: python:3.12-slim
    working_dir: /work
    volumes: [".:/work"]
    command: "sleep infinity"
    profiles: ["game"]

  network_lab:
    profiles: ["game"]
    image: nginx:1.25-alpine
    ports: ["8080:80"]
