global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['localhost:9999']  # 意図的に間違ったポート

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
