version: "3.9"
services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:8000"  # Intentionally misconfigured port mapping
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
