version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_backup_demo
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-init.sh:/docker-entrypoint-initdb.d/redis-init.sh
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backup_net

  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - backup_net

networks:
  backup_net:
    driver: bridge

volumes:
  redis_data:
